spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    username: root
    password: firoze28
    url: jdbc:mysql://localhost:3306/schooldb
    driver-class-name: com.mysql.cj.jdbc.Driver
    properties:
      hibernate:
        format_sql: true
