spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: firoze28
    url: jdbc:mysql://localhost:3306/ecomdb
server:
  port: 8085
app:
  client:
    url: http://localhost:4200/login
logging:
  level:
    org:
      springframework:
        security: debug

